services:
  php:
    build: .
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - test_network
    volumes:
      - .:/app
    working_dir: /app
    command: ["vendor/bin/tester", "-C", "."]

  mariadb:
    image: mariadb:latest

    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: test_db
    volumes:
      - type: tmpfs
        target: /var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
    networks:
      - test_network

networks:
  test_network:
    name: test_network